version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: unless-stopped

  whoami:
    build: whoami
    expose:
      - "8000"
    restart: unless-stopped